Club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('club_pages.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

club_pages/urls.py
from django.urls import path

from club_pages import views
from club_pages.views import index, fixtures_results, latest_news, home, team, detail, newsdetail
from club_pages.views import members, about, ContactUsView

urlpatterns = [

    path('index', index, name='index'),
    path('members', members.as_view(), name='members'),
    path('about-us', about.as_view(), name='about-us'),
    path('contact-us', ContactUsView.as_view(), name='contactus'),
    path('fixtures_results', fixtures_results.as_view(), name='features_result'),
    path('latest_news', latest_news.as_view(), name='latest_news'),
    path('', home.as_view(), name='home'),
    path('team', team.as_view(), name='team'),
    path('detail/<int:pid>', detail.as_view(), name='detail'),
    path('newsdetail/<int:nid>', newsdetail.as_view(), name='news_detail'),
    path('success/', views.successView, name='success'),
    # path('base',BaseView.as_view(),name='baseview')

]

club_pages/models.py
from ckeditor.fields import RichTextField
from django.db import models


def upload_player_image(instance, filename):
    return '{}/{}'.format("Players", '%s.jpg')


class PlayerType(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Player(models.Model):
    PLACE_CHOICES = (
        ('pakistan', 'PAKISTAN'),
        ('india', 'INDIA'),
        ('canada', 'CANADA'),
        ('Australia', 'AUSTRALIA'),
        ('dubai', 'DUBAI'),
        ('norway', 'NORWAY'),
    )
    name = models.CharField(max_length=250, default='SOME STRING')
    dob = models.DateField(null=True)
    birth_place = models.CharField(max_length=250, choices=PLACE_CHOICES, default='norway')
    squad_no = models.IntegerField()
    player_type = models.ForeignKey(PlayerType, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_player_image, null=True, blank=True)
    description = models.CharField(max_length=1000, default='SOME STRING')
    team = models.ForeignKey("Team", on_delete=models.CASCADE)
    email = models.EmailField(max_length=250, default='example@gmail.com')
    phone_no = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.name


class TopCategory(models.Model):
    title = models.CharField(max_length=250, default='Some String')
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    total_matches = models.IntegerField(default=0)
    tournament = models.ForeignKey('Tournament', null=True, blank=True, on_delete=models.CASCADE)
    total_wickets = models.IntegerField(default=0)
    economy_rate = models.FloatField(default=0.0)
    average = models.FloatField(default=0.0)
    total_runs = models.IntegerField(default=0)
    year = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.title


class Club(models.Model):
    name = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    club_history = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=250)
    coach_name = models.CharField(max_length=250)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    name = models.CharField(max_length=250)
    title = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Fixture(models.Model):
    T20 = 't20'
    Test = 'test'
    OneDay = 'oneday'
    Other = 'other'

    FIXTURE_TYPE = (
        (T20, 'T20'),
        (Test, 'Test'),
        (OneDay, 'One Day'),
        (Other, 'Other')
    )
    time = models.TimeField(null=True)
    date = models.DateField(null=True)
    team1 = models.ForeignKey(Team, related_name='team1', on_delete=models.CASCADE)
    team2 = models.CharField(max_length=250)
    venue = models.CharField(max_length=250)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    fixture_type = models.ForeignKey('FixtureType', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class LatestNews(models.Model):
    title = models.CharField(max_length=250)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_player_image, null=True, blank=True)

    def __str__(self):
        return self.title


class SliderImages(models.Model):
    image = models.ImageField(upload_to=upload_player_image, null=True, blank=True)

    def __str__(self):
        return str(self.id)


class SocialLink(models.Model):
    FACEBOOK = 'facebook'
    TWITTER = 'twitter'
    INSTA = 'insta'
    LINKEDIN = 'linkedin'

    TITLE_CHOICES = (
        (FACEBOOK, 'Facebook'),
        (TWITTER, 'twitter'),
        (INSTA, 'InstaGram'),
        (LINKEDIN, 'LinkedIn')
    )

    title = models.CharField(max_length=50, choices=TITLE_CHOICES, default=FACEBOOK, unique=True)
    font_awesome_icon_tag = models.CharField(max_length=30)
    url = models.URLField()

    def __str__(self):
        return self.title


class DynamicData(models.Model):
    HOME = 'home'
    ABOUT = 'about'
    FOOTER_SECTION1 = 'footer1'
    FOOTER_SECTION2 = 'footer2'
    FOOTER_SECTION3 = 'footer3'
    EMAIL = 'email'
    PHONE = 'phone'

    PAGE_DATA = (
        (HOME, 'Home'),
        (ABOUT, 'About'),
        (FOOTER_SECTION1, 'Footer1'),
        (FOOTER_SECTION2, 'Footer2'),
        (FOOTER_SECTION3, 'Footer3'),
        (EMAIL, 'Email'),
        (PHONE, 'Phone'),
    )

    page_data = models.CharField(max_length=250, choices=PAGE_DATA, default=HOME)
    text = RichTextField(null=True, blank=True)

    def __str__(self):
        return str(self.id)


class Sponser(models.Model):
    image = models.ImageField(upload_to=upload_player_image, null=True, blank=True)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return str(self.id)


class FixtureType(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

club_pages/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

club_pages/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from Club import settings
# Create your views here.
from club_pages.models import Player, Fixture, LatestNews, SliderImages, TopCategory, Team, DynamicData, Sponser, \
    FixtureType, Tournament
from club_pages.utils import get_base_data
from .forms import ContactForm


class ContactUsView(generic.TemplateView):
    template_name = 'ContactUs.html'

    def post(self, request):
        # import pdb;pdb.set_trace()
        if request.method == 'GET':
            form = ContactForm()
        else:
            form = ContactForm(request.POST)
            if form.is_valid():
                subject = form.cleaned_data['subject']
                from_email = form.cleaned_data['from_email']
                msg = form.cleaned_data['message']
                name = form.cleaned_data['name']
                # message = 'This is message'
                message = "Name: " + name + "\n" + "From: " + from_email + "\n" + "Subject: " + subject + "\n" + "Message: " + msg
                try:
                    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [settings.EMAIL_HOST_USER, ],
                              fail_silently=False, )
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return redirect('contactus')
        context = get_base_data()
        context['form'] = form
        return render(request, "contactUs.html", context)

    def get(self, request, *args, **kwargs):
        context = get_base_data()
        return render(request, self.template_name, context)


def index(request):
    return render(request, 'index.html', {})


class members(generic.TemplateView):
    template_name = 'Members.html'


class about(generic.TemplateView):
    model = DynamicData
    template_name = 'About.html'

    def get(self, request, *args, **kwargs):
        dynamicdata = DynamicData.objects.filter(page_data=DynamicData.ABOUT).first()
        context = get_base_data()
        context['about_text'] = dynamicdata
        return render(request, self.template_name, context)


class fixtures_results(generic.TemplateView):
    model = Fixture
    template_name = 'Feature_Result.html'

    def get(self, request, *args, **kwargs):
        fixtures = Fixture.objects.all().order_by('date')
        context = get_base_data()
        context['fixtures'] = fixtures
        context['fixture_types'] = Tournament.objects.all()
        return render(request, self.template_name, context)


class latest_news(generic.TemplateView):
    model = LatestNews
    template_name = 'Latest_News.html'

    def get(self, request, *args, **kwargs):
        news = LatestNews.objects.all()
        context = get_base_data()
        context['news'] = news
        return render(request, self.template_name, context)


class home(generic.TemplateView):
    model = LatestNews, Fixture, DynamicData
    template_name = 'Home.html'

    def get(self, request, *args, **kwargs):
        news = LatestNews.objects.all()
        sliderImages = SliderImages.objects.all()
        top_category = TopCategory.objects.all()
        dynamicdata = DynamicData.objects.filter(page_data=DynamicData.HOME).first()
        upcomming_mathes = Fixture.objects.filter(date__gt=timezone.now().date()).order_by('date')[:3]

        context = get_base_data()
        context['news'] = news
        context['sliderImages'] = sliderImages
        context['top_category'] = top_category
        context['home_text'] = dynamicdata
        context['upcomming_mathes'] = upcomming_mathes
        return render(request, self.template_name, context)


class team(generic.TemplateView):
    template_name = 'Team.html'

    def get(self, request, *args, **kwargs):
        players = Player.objects.all()
        first_team = Team.objects.all()[:1]
        teams = Team.objects.all()[0:]
        context = get_base_data()
        context['players'] = players
        context['first_team'] = first_team
        context['teams'] = teams
        return render(request, self.template_name, context)


class detail(generic.TemplateView):
    model = Player
    template_name = 'Player_Detail.html'

    def get(self, request, *args, **kwargs):
        pid = kwargs.get('pid')
        player_detail = Player.objects.get(id=pid)
        context = get_base_data()
        context['player_detail'] = player_detail
        return render(request, self.template_name, context)


class newsdetail(generic.TemplateView):
    model = LatestNews

    template_name = 'News_Detail.html'

    def get(self, request, *args, **kwargs):
        nid = kwargs.get('nid')
        news_detail = LatestNews.objects.get(id=nid)
        news = LatestNews.objects.all()
        context = get_base_data()
        context['news_detail'] = news_detail
        context['news'] = news

        return render(request, self.template_name, context)


class topcategory(generic.TemplateView):
    model = TopCategory
    template_name = 'Home.html'

    def get(self, request, *args, **kwargs):
        top_category = TopCategory.objects.all()
        context = get_base_data()
        context['top_category'] = top_category
        return render(request, self.template_name, context)


def successView(request):
    return HttpResponse('Success! Thank you for your message.')

club_pages/templates/About.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wide title-bar-bg animated zoomIn">
<img class="img-responsive" src="{% static 'images/about1.jpg' %}" style="    width: 100%;height: auto;"/>
<div class="container title-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="text-center title">
                    <h1 class="title-heading"></h1>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div><!-- /.container -->
</div>

<div class="container title-bottom-section">
    <div class="row">

        <div class="col-md-12">
            <div class="basic-page--text">
            {% if about_text %}
                <p>{{ about_text.text|safe }}</p>
            {% endif %}
            </div>

        </div>


    </div>
</div>


{% endblock content %}

club_pages/templates/ContactUs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="wide title-bar-bg animated zoomIn">
        <img class="img-responsive" src="{% static 'images/contact.jpg' %}" style="    width: 100%;height: auto;"/>
        <div class="container title-bar">
            <div class="container">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="text-center title">
                            <h1 class="title-heading"></h1>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </div><!-- /.container -->
    </div>




    <section class="section">

        <!--Section heading-->
        <h2 class="section-heading h1 pt-4">Contact us</h2>
        <!--Section description-->
        <p class="section-description">Do you have any questions? Please do not hesitate to contact us directly. Our
            team will come back to you within
            matter of hours to help you.</p>
        <div class="container">
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 col-xl-9">
                    <form id="contact-form" name="contact-form" action="" method="post">
                        {% csrf_token %}

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="text" id="name" name="name" class="form-control"
                                           placeholder="Your Name">

                                </div>
                            </div>
                            <!--Grid column-->

                            <!--Grid column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    <input type="email" id="email" name="from_email" class="form-control"
                                           placeholder="Your email">
                                </div>
                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->

                        <!--Grid row-->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="md-form">
                                    <input type="text" id="subject" name="subject" class="form-control"
                                           placeholder="Subject">

                                </div>
                            </div>
                        </div>
                        <!--Grid row-->

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-12">

                                <div class="md-form">
                                    <textarea type="text" id="message" name="message" rows="2"
                                              class="form-control md-textarea" placeholder="Your message"></textarea>

                                </div>

                            </div>
                        </div>
                        <!--Grid row-->
                        <div class="center-on-small-only">
                            <button class="btn btn-primary" type="submit">Send</button>
                        </div>

                    </form>


                    <div class="status"></div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 col-xl-3">
                    <ul class="contact-icons">
                        {% if phone %}
                            <li><i class="fa fa-phone fa-2x"></i>
                                <p>{{ phone.text|safe }}</p>
                            </li>
                        {% endif %}
                        {% if email %}
                            <li><i class="fa fa-envelope fa-2x"></i>
                                <p>{{ email.text|safe }}</p>
                            </li>
                        {% endif %}

                    </ul>
                </div>
                <!--Grid column-->

            </div>
        </div>

    </section>
    <!--Section: Contact v.2-->




{% endblock content %}

club_pages/templates/Feature_Result.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="wide title-bar-bg animated zoomIn">
        <img class="img-responsive" src="{% static 'images/fix.jpg' %}" style="    width: 100%;height: auto"/>
        <div class="container title-bar">
            <div class="container">
                <div class="row">

                    <div class="col-md-12">
                        <div class="text-center title">
                            <h1 class="title-heading"></h1>
                        </div>
                    </div>

                </div>
            </div>
        </div><!-- /.container -->
    </div>
    <section class="latest-news fixture-latest-news hidden-sm">
        <div class="container">
            <div class="latest-news--title-holder">
                <h2 class="latest-news--title">FIXTURES & RESULTS</h2>
            </div>
            <div class="container">

                <ul class="nav nav-pills">
                    <li class="active in active"><a data-toggle="pill" href="#menu3">All</a></li>
                    {% for fixture_type in fixture_types %}
                        <li><a data-toggle="pill" href="#{{ fixture_type.name }}">{{ fixture_type.title }}</a></li>
                    {% endfor %}

                </ul>

                <div class="tab-content">

                    {% for fixture_type in fixture_types %}
                        <div id="{{ fixture_type.name }}" class="tab-pane fade ">
                            {% for t20 in fixture_type.fixture_set.all %}
                                <div class="results row revealup fixture-strip--">

                                    <div class="results-result col-md-8 col-sm-12 col-xs-12 col-sm-12">
                                        <div class="results-result--info">
                                            <div class="results-result--date">
                                                <time datetime="2018-03-29T10:00:00Z">{{ t20.date }}</time>
                                                -
                                                <time datetime="2018-03-29T11:00:00Z">{{ t20.time }}</time>

                                            </div>
                                            <div class="results-result--text">
                                                <span>{{ t20.fixture_type }}</span>
                                                <span>- {{ t20.venue }}</span>
                                            </div>
                                        </div>
                                        <div class="results-result--team">
                                            <div class="results-result--team-logo">
                                                <div style="float:left"><img class="hidden-xs"
                                                        src="{% static 'images/transparent logo.png' %}"
                                                        alt="My image"/>
                                                    <span>{{ t20.team1.name }}</span>
                                                    <span style="margin-right: 5px">VS</span>
                                                </div>

                                                <div style="float:left">
                                                    <img class="hidden-xs" src="{% static 'images/hampshire_t20_2018_0.png' %}"
                                                         alt="My image"/>
                                                    <span>{{ t20.team2 }}</span>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                    <div class="results-result col-md-4 col-sm-12 col-xs-12 col-sm-12 hidden-xs">
                                        <img src="{% static 'images/transparent logo.png' %}" alt="My image"/>
                                    </div>

                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}


                    <div id="menu3" class="tab-pane fade in active">
                        {% for fixture in fixtures %}
                            <div class="results row revealup fixture-strip--">

                                <div class="results-result col-md-8 col-sm-12 col-xs-12 col-sm-12">
                                    <div class="results-result--info">
                                        <div class="results-result--date">
                                            <time datetime="2018-03-29T10:00:00Z">{{ fixture.date }}</time>
                                            -
                                            <time datetime="2018-03-29T11:00:00Z">{{ fixture.time }}</time>

                                        </div>
                                        <div class="results-result--text">
                                            <span>{{ fixture.fixture_type }}</span>
                                            <span>- {{ fixture.venue }}</span>
                                        </div>
                                    </div>
                                    <div class="results-result--team">
                                        <div class="results-result--team-logo">
                                            <div style="float:left"><img class="hidden-xs"
                                                    src="{% static 'images/transparent logo.png' %}" alt="My image"/>
                                                <span>{{ fixture.team1.name }}</span>
                                                <span style="margin-right: 5px">VS</span>
                                            </div>

                                            <div style="float:left">
                                                <img class="hidden-xs" src="{% static 'images/hampshire_t20_2018_0.png' %}"
                                                     alt="My image"/>
                                                <span>{{ fixture.team2 }}</span>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                                <div class="results-result col-md-4 col-sm-12 col-xs-12 col-sm-12 hidden-xs">
                                    <img src="{% static 'images/transparent logo.png' %}" alt="My image"/>
                                </div>

                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>


        </div>


    </section>


{% endblock content %}

club_pages/templates/Latest_News.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wide title-bar-bg animated zoomIn">
<img class="img-responsive" src="{% static 'images/news.jpg' %}" style="    width: 100%;height: auto;"/>
<div class="container title-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="text-center title">
                    <h1 class="title-heading"></h1>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div><!-- /.container -->
</div>
<section class="latest-news hidden-sm">
    <div class="container">
        <div class="latest-news--title-holder">
            <h2 class="latest-news--title">Latest News</h2>
        </div>
    </div>
     {% for new in news %}
    <div class="lastest-news-story">

       <div class="container">
           <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="latest-news--story-img"><img style="width: 300px; height: auto;" class="wow swing img-responsive" src="{{new.image.url}}" alt="My image"/></div>
                </div>
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <div class="latest-news--story-title">{{new.title}}</div>
                    <div class="latest-news--story-date">2 Mar 2018</div>
                    <div class="latest-news--story-text">
                        {{new.description|safe}}
                    </div>
                    <a class="latest-news--story-link" href="{% url 'news_detail' new.id %}">Read More</a>
                </div>
            </div>
       </div>

    </div>
    {% endfor %}

</section>
{% endblock content %}

{% block extrajs %}
<script>

new WOW().init();

</script>
{% endblock extrajs%}

club_pages/templates/Members.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wide title-bar-bg animated zoomIn">
<img class="img-responsive" src="{% static 'images/members.jpg' %}" style="    width: 100%;height: auto;"/>
<div class="container title-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="text-center title">
                    <h1 class="title-heading"></h1>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div><!-- /.container -->
</div>

<div class="container title-bottom-section">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="basic-page--text">
                <p>We will be launching a brand new Members area in March 2018, ready for the build&nbsp;up to the start of what promises to be one of the most exciting seasons to date.</p>
                <p>From here, you'll be able to access the new LIVE streaming and video on demand service, see highlights and extended interviews, as well as behind the scenes footage and enter monthly draws and competitions.</p>
                <p>If you are a member, then don't fear - we will be in touch when the area is ready.</p>
                <p><strong>If you are not a member then you still have time to purchase by clicking the image below</strong></p>
            </div>
            <div class="basic-page--text-img">
                 <img src="{% static 'images/Membership1.jpg' %}" alt="My image"/>
            </div>
        </div>
            <div class="col-md-2"></div>
    </div>
</div>

{% endblock content %}

club_pages/templates/Team.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="wide title-bar-bg animated zoomIn">
    <img class="img-responsive" src="{% static 'images/team.jpg' %}" style="    width: 100%;height: auto;"/>
    <div class="container title-bar">
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="text-center title">
                        <h1 class="title-heading"></h1>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div><!-- /.container -->
</div>
<section class="latest-news fixture-latest-news hidden-sm">
    <div class="container">
        <div class="latest-news--title-holder">
            <h2 class="latest-news--title">TEAMS</h2>
        </div>
    </div>
</section>

<!-- Team tabs -->
<div class="container" style="    text-align: -webkit-center;">


    <ul class="nav nav-pills" style="    margin-left: 49px;">
        {% for team in teams %}
        <li><a data-toggle="pill" class='menu-{{team.id}}' href="#menu-{{team.id}}">{{team.name}}</a></li>
        {% endfor %}
    </ul>

    <div class="tab-content">
        {% for team in teams %}
        <!--<div id="menu-{{team.id}}" class="tab-pane fade {% if teams.id == 0 %} in active {% endif %}">-->
        <!--<div id="menu-{{team.id}}" class="tab-pane fade {{ forloop.counter }}in active">-->
        <!--<div id="menu-{{team.id}}" class="tab-pane fade {% if forloop.first %}{% endif %} in active">-->
        <div id="menu-{{team.id}}" class="tab-pane fade in active {% if forloop.counter0 %}active{% endif %} ">
            {% for player in team.player_set.all|dictsort:"dob" %}
            <div class="col-md-4 player">
                <div class="img-section">
                    <img class="wow swing img-responsive team-player" src="{{player.image.url}}">
                </div>
                <div class="player--name">
                    {{ player.name }}
                </div>
                <div class="player--info matchHeight">
                    <div class="player--info-text"><strong>DOB: </strong><span><time datetime="1994-07-08T12:00:00Z">
                        {{player.dob}}
                    </time>
                    </span></div>
                    <div class="player--info-text"><strong>Birthplace: </strong><span>{{ player.get_birth_place_display }}</span>
                    </div>
                    <div class="player--info-text"><strong>Squad Number: </strong><span>{{ player.squad_no }}</span>
                    </div>

                    <div class="player--info-text"><strong>Player
                        Style: </strong><span>{{ player.player_type }} </span></div>

                </div>


            </div>
            {% endfor %}
        </div>
        {%endfor%}


    </div>
</div>

{% endblock content %}

{% block extrajs %}
<script>
    document.getElementsByClassName('menu-' + '{{teams.0.id}}')[0].click()
</script>

{% endblock extrajs%}